import { renderToString } from "react-dom/server";
import { Router } from "wouter";
import App from "./App";
import { articles } from "@/lib/articles";

const origin = "https://securestack-hub.pages.dev";
const escape = (x: string) => x.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[c] as string));
export function getRoutes() { return ["/", "/category/vpn-troubleshooting/", "/about/", "/feedback/", ...articles.map((a) => `/article/${a.slug}/`)]; }
export function getRedirects() { return [...articles.map((a) => `${new URL(a.canonicalUrl).pathname} /article/${a.slug} 301`), "/article/blog-post /article/can-school-see-vpn-use 301", "/article/blog-post_09 /article/vpn-not-working-galaxy-s24 301", "/article/blog-post_504 /article/vpn-kills-wifi-connection 301", "/article/vpn-not-working-galaxy-s24-fix /article/vpn-not-working-galaxy-s24 301", "/2026/09/vpn-not-working-galaxy-s24-fix.html /article/vpn-not-working-galaxy-s24 301"]; }
export function getHead(path: string) { const article = articles.find((a) => path === `/article/${a.slug}/`); const category = path === "/category/vpn-troubleshooting/"; const feedback = path === "/feedback/"; const title = article ? `${article.title} | SecureStack Hub` : category ? "VPN Troubleshooting Guides | SecureStack Hub" : path === "/about/" ? "About SecureStack Hub | Editorial Standards" : feedback ? "Corrections & Feedback | SecureStack Hub" : "VPN Troubleshooting & Privacy Guides | SecureStack Hub"; const description = article?.description || (category ? "Straightforward VPN troubleshooting guides for Wi-Fi, DNS, devices, and local networks." : feedback ? "Send SecureStack Hub a correction or website feedback through our public feedback page." : "Straightforward VPN troubleshooting and online privacy guides with clear steps, practical limits, and no hype."); return { title, description, canonical: `${origin}${path}`, article }; }
export function render(url: string) { const path = url.split("?")[0].replace(/([^/])$/, "$1/") || "/"; const head = getHead(path); const html = renderToString(<Router ssrPath={path}><App /></Router>); const breadcrumb = head.article ? { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${origin}/` }, { "@type": "ListItem", position: 2, name: "VPN Troubleshooting", item: `${origin}/category/vpn-troubleshooting` }, { "@type": "ListItem", position: 3, name: head.article.title, item: head.canonical }] } : null; const articleSchema = head.article ? { "@context": "https://schema.org", "@type": "Article", headline: head.article.title, description: head.article.description, datePublished: head.article.publishedAt, dateModified: head.article.updatedAt, author: { "@type": "Organization", name: "SecureStack Editorial", url: `${origin}/about` }, publisher: { "@type": "Organization", name: "SecureStack Hub", url: origin }, mainEntityOfPage: head.canonical } : null; const faqSchema = head.article?.faq?.length ? { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: head.article.faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) } : null; const jsonLd = head.article ? `<script type="application/ld+json">${JSON.stringify(articleSchema)}</script>${faqSchema ? `<script type="application/ld+json">${JSON.stringify(faqSchema)}</script>` : ""}${breadcrumb ? `<script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", ...breadcrumb })}</script>` : ""}` : `<script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@type": "WebSite", name: "SecureStack Hub", url: origin })}</script>`; const meta = `<title>${escape(head.title)}</title><meta name="description" content="${escape(head.description)}"><meta name="author" content="SecureStack Editorial"><meta name="robots" content="index,follow"><meta name="google-site-verification" content="dlCrSiMy1rU3QRhcMeH4FkiKGV_rt-N4SJB_1P8HJXI"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="canonical" href="${head.canonical}">${jsonLd}`; return { html, head: meta, title: head.title, notFound: false }; }
