import { Link } from "wouter";
import { useState } from "react";
import { ArrowLeft, CheckCircle2, LogIn, Save, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { SiteLayout } from "@/components/SiteLayout";

const starter = { slug: "", title: "", description: "", category: "VPN Troubleshooting", contentHtml: "<h2>Quick answer</h2><p>Start with a concise answer that addresses the reader's problem directly.</p><h2>Step-by-step fixes</h2><ol><li><strong>First check:</strong> explain what to verify.</li><li><strong>Second check:</strong> explain the next action.</li></ol><h2>When to escalate</h2><p>Explain when the reader should contact their provider or consult official support.</p>", status: "draft" as const, authorName: "SecureStack Editorial" };

export default function EditorPage() {
  const { user, loading } = useAuth();
  const [form, setForm] = useState(starter);
  const [saved, setSaved] = useState(false);
  const create = trpc.editor.create.useMutation({ onSuccess: () => setSaved(true) });
  if (loading) return <SiteLayout><main className="container page-state">Checking editor access…</main></SiteLayout>;
  if (!user) return <SiteLayout><main className="container page-state"><p className="eyebrow">Private publishing area</p><h1>Sign in to publish</h1><p>Use the site owner account to open the editor. Public readers never see this area in search.</p><button className="button button-primary" onClick={() => startLogin()}><LogIn size={17} /> Sign in to continue</button></main></SiteLayout>;
  return <SiteLayout><main className="container editor-page"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to site</Link><div className="editor-header"><div><p className="eyebrow"><Sparkles size={14} /> Publishing workflow</p><h1>Write a new guide</h1><p>Save a draft, then publish when title, summary, sources, and internal links are ready.</p></div><div className="editor-status"><CheckCircle2 size={17} /> Owner access</div></div><form className="editor-form" onSubmit={(e) => { e.preventDefault(); setSaved(false); create.mutate(form); }}><label>Title<input required value={form.title} onChange={(e) => setForm({...form,title:e.target.value})} placeholder="VPN not working on Windows? 7 fixes" /></label><label>URL slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={(e) => setForm({...form,slug:e.target.value})} placeholder="vpn-not-working-windows-fixes" /></label><label>Meta description<textarea required minLength={50} maxLength={320} value={form.description} onChange={(e) => setForm({...form,description:e.target.value})} placeholder="A clear 150–160 character summary…" /></label><div className="form-two"><label>Category<select value={form.category} onChange={(e) => setForm({...form,category:e.target.value})}><option>VPN Troubleshooting</option><option>Privacy Explain­ers</option><option>Streaming Access</option><option>Device Guides</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({...form,status:e.target.value as any})}><option value="draft">Draft</option><option value="published">Publish now</option></select></label></div><label>Article HTML<textarea className="content-editor" required value={form.contentHtml} onChange={(e) => setForm({...form,contentHtml:e.target.value})} /></label><div className="editor-help"><strong>Publishing checklist:</strong> include a direct answer, 3–7 useful steps, original testing notes, authoritative source links, a named author, and 4 contextual internal links before publishing.</div><button className="button button-primary" disabled={create.isPending}><Save size={17} /> {create.isPending ? "Saving…" : "Save article"}</button>{saved && <p className="save-success"><CheckCircle2 size={16} /> Article saved successfully.</p>}{create.error && <p className="error-text">{create.error.message}</p>}</form></main></SiteLayout>;
}
